Watching for file changes with StatReloader
C:\Users\roade\OneDrive\Documents\Desktop\Hood-Hockey\capstone\hood_hockey_app\views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 07, 2025 - 11:47:46
Django version 5.1.7, using settings 'capstone.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

Watching for file changes with StatReloader
Unauthorized: /hood_hockey_app/games/
[07/Mar/2025 11:51:36] "GET /hood_hockey_app/games/ HTTP/1.1" 401 172
Unauthorized: /hood_hockey_app/games/
[07/Mar/2025 11:51:36] "GET /hood_hockey_app/games/ HTTP/1.1" 401 172
[07/Mar/2025 11:51:52] "OPTIONS /hood_hockey_app/token/ HTTP/1.1" 200 0
Unauthorized: /hood_hockey_app/token/
[07/Mar/2025 11:51:54] "POST /hood_hockey_app/token/ HTTP/1.1" 401 63
[07/Mar/2025 11:52:08] "POST /hood_hockey_app/token/ HTTP/1.1" 200 483
[07/Mar/2025 11:52:48] "GET /hood_hockey_app/games/ HTTP/1.1" 200 48306
[07/Mar/2025 11:52:49] "GET /hood_hockey_app/games/ HTTP/1.1" 200 48306
[07/Mar/2025 11:53:02] "OPTIONS /hood_hockey_app/user/register/ HTTP/1.1" 200 0
[07/Mar/2025 11:53:04] "POST /hood_hockey_app/user/register/ HTTP/1.1" 201 30
[07/Mar/2025 11:53:14] "POST /hood_hockey_app/token/ HTTP/1.1" 200 483
[07/Mar/2025 11:53:20] "GET /hood_hockey_app/games/ HTTP/1.1" 200 2
[07/Mar/2025 11:53:20] "GET /hood_hockey_app/games/ HTTP/1.1" 200 2
[07/Mar/2025 11:53:52] "POST /hood_hockey_app/games/ HTTP/1.1" 201 2309
[07/Mar/2025 11:53:53] "GET /hood_hockey_app/games/ HTTP/1.1" 200 2311
Internal Server Error: /hood_hockey_app/upload-file/
[07/Mar/2025 11:54:13] "POST /hood_hockey_app/upload-file/ HTTP/1.1" 500 109
Method Not Allowed: /hood_hockey_app/upload-file/
[07/Mar/2025 11:54:59] "GET /hood_hockey_app/upload-file/ HTTP/1.1" 405 5735
C:\Users\roade\OneDrive\Documents\Desktop\Hood-Hockey\capstone\hood_hockey_app\views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 07, 2025 - 11:51:23
Django version 5.1.7, using settings 'capstone.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

{'username': 'adrianna', 'password': 'password'}
Watching for file changes with StatReloader
[07/Mar/2025 12:05:14] "GET /hood_hockey_app/games/ HTTP/1.1" 200 2311
[07/Mar/2025 12:05:14] "GET /hood_hockey_app/games/ HTTP/1.1" 200 2311
Internal Server Error: /hood_hockey_app/upload-file/
[07/Mar/2025 12:05:24] "POST /hood_hockey_app/upload-file/ HTTP/1.1" 500 235
C:\Users\roade\OneDrive\Documents\Desktop\Hood-Hockey\capstone\hood_hockey_app\views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 07, 2025 - 11:59:09
Django version 5.1.7, using settings 'capstone.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

Watching for file changes with StatReloader
[07/Mar/2025 12:06:29] "GET /hood_hockey_app/games/ HTTP/1.1" 200 2311
[07/Mar/2025 12:06:30] "GET /hood_hockey_app/games/ HTTP/1.1" 200 2311
[07/Mar/2025 12:06:40] "POST /hood_hockey_app/upload-file/ HTTP/1.1" 201 51
C:\Users\roade\OneDrive\Documents\Desktop\Hood-Hockey\capstone\capstone\settings.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 07, 2025 - 12:06:23
Django version 5.1.7, using settings 'capstone.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

Watching for file changes with StatReloader
[07/Mar/2025 12:16:54] "GET /hood_hockey_app/games/ HTTP/1.1" 200 2311
[07/Mar/2025 12:16:54] "GET /hood_hockey_app/games/ HTTP/1.1" 200 2311
[07/Mar/2025 12:17:09] "POST /hood_hockey_app/token/ HTTP/1.1" 200 483
[07/Mar/2025 12:17:13] "GET /hood_hockey_app/games/ HTTP/1.1" 200 48306
[07/Mar/2025 12:17:13] "GET /hood_hockey_app/games/ HTTP/1.1" 200 48306
[07/Mar/2025 12:17:42] "POST /hood_hockey_app/games/ HTTP/1.1" 201 2299
[07/Mar/2025 12:17:43] "GET /hood_hockey_app/games/ HTTP/1.1" 200 50606
[07/Mar/2025 12:17:52] "POST /hood_hockey_app/upload-file/ HTTP/1.1" 201 51
[07/Mar/2025 12:18:37] "POST /hood_hockey_app/upload-file/ HTTP/1.1" 201 51
C:\Users\roade\OneDrive\Documents\Desktop\Hood-Hockey\capstone\hood_hockey_app\views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 07, 2025 - 12:16:20
Django version 5.1.7, using settings 'capstone.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

Watching for file changes with StatReloader
C:\Users\roade\OneDrive\Documents\Desktop\Hood-Hockey\capstone\hood_hockey_app\views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 07, 2025 - 12:20:31
Django version 5.1.7, using settings 'capstone.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

Watching for file changes with StatReloader
C:\Users\roade\OneDrive\Documents\Desktop\Hood-Hockey\capstone\hood_hockey_app\views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 07, 2025 - 12:22:25
Django version 5.1.7, using settings 'capstone.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\roade\AppData\Local\Programs\Python\Python313\Lib\threading.py", line 1041, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "C:\Users\roade\AppData\Local\Programs\Python\Python313\Lib\threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roade\OneDrive\Documents\Desktop\Hood-Hockey\env\Lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
    ~~^^^^^^^^^^^^^^^^^
  File "C:\Users\roade\OneDrive\Documents\Desktop\Hood-Hockey\env\Lib\site-packages\django\core\management\commands\runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roade\OneDrive\Documents\Desktop\Hood-Hockey\env\Lib\site-packages\django\core\management\base.py", line 486, in check
    all_issues = checks.run_checks(
        app_configs=app_configs,
    ...<2 lines>...
        databases=databases,
    )
  File "C:\Users\roade\OneDrive\Documents\Desktop\Hood-Hockey\env\Lib\site-packages\django\core\checks\registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "C:\Users\roade\OneDrive\Documents\Desktop\Hood-Hockey\env\Lib\site-packages\django\core\checks\urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "C:\Users\roade\OneDrive\Documents\Desktop\Hood-Hockey\env\Lib\site-packages\django\core\checks\urls.py", line 26, in check_resolver
    return check_method()
  File "C:\Users\roade\OneDrive\Documents\Desktop\Hood-Hockey\env\Lib\site-packages\django\urls\resolvers.py", line 531, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\roade\OneDrive\Documents\Desktop\Hood-Hockey\env\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\roade\OneDrive\Documents\Desktop\Hood-Hockey\env\Lib\site-packages\django\urls\resolvers.py", line 718, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roade\OneDrive\Documents\Desktop\Hood-Hockey\env\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\roade\OneDrive\Documents\Desktop\Hood-Hockey\env\Lib\site-packages\django\urls\resolvers.py", line 711, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\roade\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\roade\OneDrive\Documents\Desktop\Hood-Hockey\capstone\capstone\urls.py", line 12, in <module>
    path("hood_hockey_app/", include("hood_hockey_app.urls")),
                             ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roade\OneDrive\Documents\Desktop\Hood-Hockey\env\Lib\site-packages\django\urls\conf.py", line 39, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Users\roade\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\roade\OneDrive\Documents\Desktop\Hood-Hockey\capstone\hood_hockey_app\urls.py", line 3, in <module>
    from .views import FileUploadView
ImportError: cannot import name 'FileUploadView' from 'hood_hockey_app.views' (C:\Users\roade\OneDrive\Documents\Desktop\Hood-Hockey\capstone\hood_hockey_app\views.py)
C:\Users\roade\OneDrive\Documents\Desktop\Hood-Hockey\capstone\hood_hockey_app\urls.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
[07/Mar/2025 12:32:55] "GET /hood_hockey_app/games/ HTTP/1.1" 200 50606
[07/Mar/2025 12:32:55] "GET /hood_hockey_app/games/ HTTP/1.1" 200 50606
[07/Mar/2025 12:33:03] "POST /hood_hockey_app/token/ HTTP/1.1" 200 483
[07/Mar/2025 12:33:08] "GET /hood_hockey_app/games/ HTTP/1.1" 200 50606
[07/Mar/2025 12:33:08] "GET /hood_hockey_app/games/ HTTP/1.1" 200 50606
[07/Mar/2025 12:33:18] "OPTIONS /hood_hockey_app/games-upload-file/ HTTP/1.1" 200 0
[07/Mar/2025 12:33:19] "POST /hood_hockey_app/games-upload-file/ HTTP/1.1" 201 51
[07/Mar/2025 12:33:47] "POST /hood_hockey_app/games/ HTTP/1.1" 201 2299
[07/Mar/2025 12:33:49] "GET /hood_hockey_app/games/ HTTP/1.1" 200 52906
